let districtList = [
//DHAKA, KHULNA & CHITTAGONG District list
	{ name: "Dhaka" , code: "DKH"},
	{ name: "Faridpur" , code: "FAP"},
	{ name: "Gazipur" , code: "GZP"},
	{ name: "Gopalganj" , code: "GPZ"},
	{ name: "Jamalpur" , code: "JPR"},
	{ name: "Kishoreganj" , code: "KNG"},
	{ name: "Madaripur", code: "MPR"},
	{ name: "Manikganj", code: "MNJ"},
	{ name: "Munshiganj", code: "MNJ"},
	{ name: "Mymensingh", code: "MNH"},
	{ name: "Narayanganj", code: "NYJ"},
	{ name: "Narsingdi", code: "NDI"},
	{ name: "Netrokona", code: "NKA"},
	{ name: "Rajbari", code: "RBI"},
	{ name: "Shariatpur", code: "SPR"},
	{ name: "Sherpur", code: "SHR"},
	{ name: "Tangail", code: "TAL"},
	{ name: "Bagerhat", code: "BGT"},
	{ name: "Chuadanga", code: "CGA"},
	{ name: "Jessore", code: "JSR"},
	{ name: "Jhenaidaha", code: "JHA"},
	{ name: "Khulna", code: "KLA"},
	{ name: "Kushtia", code: "KUA"},
	{ name: "Magura", code: "MGA"},
	{ name: "Meherpur", code: "MER"},
	{ name: "Narail", code: "NIL"},
	{ name: "Satkhira", code: "SRA"},
	{ name: "Bandarban", code: "BBA"},
	{ name: "Brahmanbaria", code: "BMA"},
	{ name: "Chandpur", code: "CPR"},
	{ name: "Chittagong", code: "CTG"},
	{ name: "Comilla", code: "COM"},
	{ name: "Cox's Bazar", code: "CBZ"},
	{ name: "Feni", code: "FNI"},
	{ name: "Khagrachhari", code: "KCI"},
	{ name: "Lakshmipur", code: "LMP"},
	{ name: "Noakhali", code: "NKI"},
	{ name: "Rangamati", code: "RTI"}
];

export {districtList}; // Named Module Export